### ISSUE TITLE
Add instance methods to pyTorch frontend

### ISSUE THREAD

**Issue by Anthonia24** [unifyai/ivy#5859] opened 2022-10-18 05:44 UTC

**Comment by AnnaTz** [comment] 2022-10-21 10:53
Hi @Anthonia24! There is already an issue for adding instance methods to the pytorch frontend (here #3612), so I'll be closing your issue as duplicate. If what you meant to do was to contribute an instance method, then you should create an issue named as this specific method and link it to the corresponding bullet in #3612.

**Comment by AnnaTz** [comment] 2022-10-21 10:53
Issue duplicate of #3612.

**Closed by AnnaTz** 2022-10-21 10:53 UTC
